### ISSUE TITLE
Got Gerudo Mask instead of item

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#257]
LuckE Today at 3:22 AM
https://cdn.discordapp.com/attachments/313327428703485953/508902050466365450/unknown.png

got gerudo mask instead of small key
in shadow temple
CR2ARSBKMPAAYZN4HA8A - settings string
with the hot swap boots version

**Comment by phixtyseven** [comment]
While I'm sorry that happened I also think it's hilarious.

**Comment by TestRunnerSRL** [comment]
I'm unsure what would cause this, however there has since been a refactor of the get item code to be a lot more reliable. Also this bug report is a dead link, so any kind of reproducability would be pretty impossible

**Comment by r0bd0g** [comment]
This apparently is still happening

**Comment by pidgezero-one** [comment]
> This apparently is still happening?
> 
> pidgezero_one Today at 3:03 PM
> world 1 gohma prize drop model was a triforce piece, i picked it up and it gave me a gerudo mask

This was the seed in question:

https://ootrandomizer.com/seed/get?id=668302 

Was using the Dec. 7 merge of the multiworld repo master branch

**Comment by r0bd0g** [comment]
This issue should not have been closed. It still occurs even today.

**Comment by fenhl** [comment]
Got another instance of this in <https://ootrandomizer.com/seed/get?id=1266725>. Player 3 found a Gerudo mask instead of a Triforce piece from Gerudo Training Ground Heavy Block First Chest.

**Comment by fenhl** [comment]
The player reports that when resetting and opening the chest again, the item became a Triforce piece.

**Comment by ETR-BTF** [comment]
They all seem to be Triforce Pieces. 1-2 years ago I played a MW and someone also got this bug when the model was a Triforce Piece (crater wall freestanding item). Iirc they didn't have to repatch, but just quit (without saving) and pick up the item again.

**Comment by fenhl** [comment]
So it's likely only Triforce pieces in multiworld now and doesn't happen anymore for other items or in singleplayer. But it obviously doesn't happen every time, we've had a few Triforce Hunt seeds in [S4](https://midos.house/event/mw/4) and no reports of this yet. It's also most likely a bug in the randomizer, as it has been happening both to [bizhawk-co-op](https://github.com/TestRunnerSRL/bizhawk-co-op) users (e.g. the report from @pidgezero-one) and to [Mido's House Multiworld](https://midos.house/mw) users (e.g. the report I posted).

If anyone has any ideas on where this could be coming from or has noticed something else the occurrences of this bug have in common, please post a comment.

**Comment by fenhl** [comment]
Now that trade quest shuffle is a thing, we may want to introduce a dedicated “error” item or use an item that's unused in vanilla instead of using the Gerudo mask, because right now players running into this issue may not even realize it.

**Comment by fenhl** [comment]
Had [another instance of this](https://www.twitch.tv/bread_kun/clip/TriumphantTrustworthyAlligatorSSSsss-Pkr-c9_L9veee-YA) happen in the multiworld tournament today, but this time the item was supposed to be iron boots. However, it was still a Triforce hunt and the player was in fact _receiving_ a Triforce piece at the same time. This leads me to believe that maybe the special handling for incoming Triforce pieces has a race condition with own/outgoing overrides. With this information, I found a likely culprit, which I've fixed in #2406.

**Comment by fenhl** [comment]
Another instance which matches my hypothesis: [Natheirean](https://youtu.be/d_TmcNBfoW4?t=7871) opens a chest which is supposed to contain a Triforce piece while simultaneously receiving a piece from [Pyra](https://youtu.be/m_ESV-__FgE?t=8051) (links are timestamped vods). The piece from the chest turns into a Gerudo mask.

**Comment by Naestriel1** [comment]
FYI looks like this is still present - 4 player TFB settings multiworld, player 4 was climbing GV ladder as adult when player 2 collected a piece. At the top of the ladder, player 4 immediately received notification that a new triforce piece was collected & grabbed Din's Fire for player 3. They then held Gerudo Mask over their head & player 3 did not receive the Din's until player 4 created a new save & recollected the check.

Clip - https://youtu.be/COYI-kuFKs0

Player 2's view, players 3 & 4 in top right from left to right respectively.

**Comment by flagrama** [comment]
~~This was on version 9.1,13 or newer? A spoiler posted on July 17 implies TFB is still on 9.1.9~~ Triforce Blitz is on an old version, 9.1.9. This bug was fixed in 9.1.13.

I just generated this seed on the website:
```
ID
f1849ac2-063b-4663-996d-1b584ad67eaf
Generation status
Ready
Generation attempts
1
Triforce Blitz release
v9.1.9-blitz-1.16
Settings preset
Triforce Blitz S5
Triforce Blitz season
Triforce Blitz S5
Generator version
9.1.9 blitz-115
Settings string
BSAJH2EAUCBAENLEASAUSEEKTAAUJLDCEAAAABABAJCA2DA2CAAEAETSAAEAELBLFJVCQL6KBQJAASAGADWBRAJ6U8JJRCWQXALSD6EXL4CAAABAEMQBAC2HPJNPAZDACGJNA6BSDJAJTA3JGJ
Requested at
July 30, 2026 at 9:23:42 AM UTC
Generated at
July 30, 2026 at 9:23:49 AM UTC
```

**Comment by Naestriel1** [comment]
Confirmed, Seed generated on Dev TFBlitz v9.1.9-115
